// Auto-generated by scripts/generate-model-configs.ts
// Do not edit manually.

export const MODEL_CONFIGS: Record<string, { editableParts: { id: string; meshName: string; label: string }[] }> = {
  "Chair.glb": {
    "editableParts": [
      {
        "id": "node",
        "meshName": "Node",
        "label": "Node"
      }
    ]
  },
  "Window.glb": {
    "editableParts": [
      {
        "id": "node",
        "meshName": "Node",
        "label": "Node"
      }
    ]
  },
  "Bicycle.glb": {
    "editableParts": [
      {
        "id": "bike-mesh",
        "meshName": "Bike_mesh",
        "label": "Bike mesh"
      }
    ]
  },
  "Kettlebell.glb": {
    "editableParts": [
      {
        "id": "kettlebell-q",
        "meshName": "Kettlebell_Q",
        "label": "Kettlebell  Q"
      }
    ]
  },
  "Exercise Bike.glb": {
    "editableParts": [
      {
        "id": "mesh1-group1-model",
        "meshName": "Mesh1 Group1 Model",
        "label": "Mesh1  Group1  Model"
      },
      {
        "id": "mesh2-model",
        "meshName": "Mesh2 Model",
        "label": "Mesh2  Model"
      },
      {
        "id": "mesh3-model",
        "meshName": "Mesh3 Model",
        "label": "Mesh3  Model"
      },
      {
        "id": "mesh4-model",
        "meshName": "Mesh4 Model",
        "label": "Mesh4  Model"
      },
      {
        "id": "mesh5-model",
        "meshName": "Mesh5 Model",
        "label": "Mesh5  Model"
      },
      {
        "id": "mesh6-model",
        "meshName": "Mesh6 Model",
        "label": "Mesh6  Model"
      },
      {
        "id": "mesh7-model",
        "meshName": "Mesh7 Model",
        "label": "Mesh7  Model"
      },
      {
        "id": "mesh8-model",
        "meshName": "Mesh8 Model",
        "label": "Mesh8  Model"
      },
      {
        "id": "mesh9-model",
        "meshName": "Mesh9 Model",
        "label": "Mesh9  Model"
      },
      {
        "id": "mesh10-model",
        "meshName": "Mesh10 Model",
        "label": "Mesh10  Model"
      },
      {
        "id": "mesh11-model",
        "meshName": "Mesh11 Model",
        "label": "Mesh11  Model"
      },
      {
        "id": "mesh12-model",
        "meshName": "Mesh12 Model",
        "label": "Mesh12  Model"
      },
      {
        "id": "mesh13-model",
        "meshName": "Mesh13 Model",
        "label": "Mesh13  Model"
      }
    ]
  },
  "Treadmill.glb": {
    "editableParts": [
      {
        "id": "treadmill",
        "meshName": "Treadmill",
        "label": "Treadmill"
      }
    ]
  },
  "Fan.glb": {
    "editableParts": [
      {
        "id": "sphere",
        "meshName": "Sphere",
        "label": "Sphere"
      },
      {
        "id": "cylinder",
        "meshName": "Cylinder",
        "label": "Cylinder"
      },
      {
        "id": "cylinder-001",
        "meshName": "Cylinder.001",
        "label": "Cylinder.001"
      },
      {
        "id": "cylinder-002",
        "meshName": "Cylinder.002",
        "label": "Cylinder.002"
      },
      {
        "id": "cylinder-003",
        "meshName": "Cylinder.003",
        "label": "Cylinder.003"
      },
      {
        "id": "cylinder-004",
        "meshName": "Cylinder.004",
        "label": "Cylinder.004"
      },
      {
        "id": "plane",
        "meshName": "Plane",
        "label": "Plane"
      },
      {
        "id": "cylinder-005",
        "meshName": "Cylinder.005",
        "label": "Cylinder.005"
      },
      {
        "id": "cylinder-006",
        "meshName": "Cylinder.006",
        "label": "Cylinder.006"
      }
    ]
  },
  "Couch Small.glb": {
    "editableParts": [
      {
        "id": "couch-small2",
        "meshName": "Couch_Small2",
        "label": "Couch  Small2"
      }
    ]
  },
  "Flat Screen TV.glb": {
    "editableParts": [
      {
        "id": "group1257628551",
        "meshName": "group1257628551",
        "label": "group1257628551"
      },
      {
        "id": "group1454904968",
        "meshName": "group1454904968",
        "label": "group1454904968"
      },
      {
        "id": "group1840578182",
        "meshName": "group1840578182",
        "label": "group1840578182"
      },
      {
        "id": "group596176051",
        "meshName": "group596176051",
        "label": "group596176051"
      },
      {
        "id": "group397977436",
        "meshName": "group397977436",
        "label": "group397977436"
      },
      {
        "id": "group1562963861",
        "meshName": "group1562963861",
        "label": "group1562963861"
      },
      {
        "id": "group1468930754",
        "meshName": "group1468930754",
        "label": "group1468930754"
      },
      {
        "id": "group1923268096",
        "meshName": "group1923268096",
        "label": "group1923268096"
      },
      {
        "id": "group207519990",
        "meshName": "group207519990",
        "label": "group207519990"
      },
      {
        "id": "group108534205",
        "meshName": "group108534205",
        "label": "group108534205"
      },
      {
        "id": "group83437352",
        "meshName": "group83437352",
        "label": "group83437352"
      },
      {
        "id": "group2052255221",
        "meshName": "group2052255221",
        "label": "group2052255221"
      },
      {
        "id": "group1457147635",
        "meshName": "group1457147635",
        "label": "group1457147635"
      },
      {
        "id": "group1601593260",
        "meshName": "group1601593260",
        "label": "group1601593260"
      }
    ]
  },
  "Couch Large.glb": {
    "editableParts": [
      {
        "id": "couch-large1",
        "meshName": "Couch_Large1",
        "label": "Couch  Large1"
      }
    ]
  }
};
